allowBuilds:
  '@ffprobe-installer/darwin-arm64': true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - protobufjs@7.6.3
  - tar@7.5.16
  - protobufjs@7.6.1
  - undici@6.27.0
